Ninesky.Web/Areas/System/Controllers/ContentController.cs
/*======================================
 作者：洞庭夕照
 创建：2017.04.18
 网站：www.ninesky.cn
       mzwhj.cnblogs.com
 代码：git.oschina.net/ninesky/Ninesky
 论坛：bbs.ninesky.cn
 版本：v1.0.0.0
 =====================================*/
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Ninesky.InterfaceBase;
using Ninesky.Models;

namespace Ninesky.Web.Areas.System.Controllers
{
    /// <summary>
    /// 内容控制器
    /// </summary>
    [Area("system")]
    public class ContentController : Controller
    {
        private InterfaceContentService _contentService;

        public ContentController(InterfaceContentService contentService)
        {
            _contentService = contentService;
        }
        public IActionResult Index()
        {
            return View();
        }

        /// <summary>
        ///内容列表 
        /// </summary>
        /// <returns></returns>
        public IActionResult List()
        {
            return View();
        }

        /// <summary>
        /// 修改内容
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public async Task<IActionResult> Modify(int id)
        {
            var moduleType = await _contentService.FindModuleTypeAsync(id);
            switch(moduleType)
            {
                case ModuleType.Article:
                return View("ModifyArticle", await _contentService.FindAsync(id));
                default:
                    return Content("内容模型错误！");
            }
            
        }

        /// <summary>
        /// 查找Ajax
        /// </summary>
        /// <param name="title">标题</param>
        /// <param name="inputer">录入者</param>
        /// <param name="contentId">内容Id</param>
        /// <param name="categoryId">栏目Id</param>
        /// <param name="order">排序方式</param>
        /// <returns></returns>
        public async Task<JsonResult> SearchAjaxAsync(int? status,string title, string inputer, int contentId = 0, int categoryId = 0, int pageIndex = 1, int pageSize = 20, int order = 0)
        {
            Paging<Content> contentPaging;
            if(status == null) contentPaging = await _contentService.FindListAsync(null, title, inputer, contentId, categoryId, pageIndex, pageSize, (ContentOrder)order);
            else contentPaging = await _contentService.FindListAsync((ContentStatus)status, title, inputer, contentId, categoryId, pageIndex, pageSize, (ContentOrder)order);
            return Json(new { total = contentPaging.Total, rows = contentPaging.Entities });
        }
    }
}

Ninesky.Web/Areas/System/Controllers/ModuleController.cs
/*======================================
 作者：洞庭夕照
 创建：2016.12.28
 网站：www.ninesky.cn
       mzwhj.cnblogs.com
 代码：git.oschina.net/ninesky/Ninesky
 版本：v1.0.0.0
 =====================================*/
using Microsoft.AspNetCore.Mvc;
using Ninesky.InterfaceBase;
using Ninesky.Web.Models;
using System.Linq;
using System.Threading.Tasks;

namespace Ninesky.Web.Areas.System.Controllers
{
    [Area("System")]
    public class ModuleController : Controller
    {
        private InterfaceModuleService _moduleService;

        public ModuleController(InterfaceModuleService moduleService)
        {
            _moduleService = moduleService;
        }

        /// <summary>
        /// 详细
        /// </summary>
        /// <param name="id">模块ID</param>
        /// <returns></returns>
        public async Task<IActionResult> Details(int id)
        {
            return View(await _moduleService.FindAsync(id));
        }

        [HttpPost]
        public async Task<IActionResult> Enable (int id, bool enabled)
        {
            JsonResponse jsonResponse = new JsonResponse();
            var module = await _moduleService.FindAsync(id);
            if(module == null)
            {
                jsonResponse.succeed = false;
                jsonResponse.message = "模块不存在";
            }
            else
            {
                module.Enabled = enabled;
                var oResult = await _moduleService.UpdateAsync(module);
                if(oResult.Succeed)
                {
                    jsonResponse.succeed = true;
                    jsonResponse.message = "模块已" + (enabled ? "启用" : "禁用");
                }
                else
                {
                    jsonResponse.succeed = false;
                    jsonResponse.message = "保存数据失败";
                }
            }
            return Json(jsonResponse);
        }

        public IActionResult Index()
        {
            return View();
        }
        /// <summary>
        /// 模块列表
        /// </summary>
        /// <returns></returns>
        public async Task<IActionResult> List()
        {
            return Json((await _moduleService.FindListAsync()).ToList());
        }
    }
}

Ninesky.Web/Controllers/CategoryController.cs
/*======================================
 作者：洞庭夕照
 创建：2016.12.03
 网站：www.ninesky.cn
       mzwhj.cnblogs.com
 代码：git.oschina.net/ninesky/Ninesky
 版本：v1.0.0.0
 =====================================*/

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Ninesky.InterfaceBase;
using Ninesky.Models;


namespace Ninesky.Web.Controllers
{
    /// <summary>
    /// 栏目控制器
    /// </summary>
    public class CategoryController : Controller
    {

        /// <summary>
        /// 栏目服务
        /// </summary>
        private InterfaceCategoryService _categoryService;

        public CategoryController(InterfaceCategoryService categoryService)
        {
            _categoryService = categoryService;
        }

        /// <summary>
        /// 查看栏目
        /// </summary>
        /// <param name="id">栏目Id</param>
        /// <returns></returns>
        [Route("/Category/{id:int}")]
        public async Task<IActionResult> Index(int id)
        {
            var category = await _categoryService.FindAsync(id);
            if (category == null) return View("Error", new Models.Error { Title = "错误消息", Name="栏目不存在", Description="访问ID为【"+id+"】的栏目时发生错误，该栏目不存在。" });
            switch (category.Type)
            {
                case CategoryType.General:
                    
                    return View(category.View, category);
                case CategoryType.Page:
                    
                    return View(category.View, category);
                case CategoryType.Link:

                    return Redirect(category.LinkUrl);
                default:
                    return View("Error", new Models.Error { Title = "错误消息", Name = "栏目数据错误", Description = "栏目【" + category.Name + "】的类型错误。" });

            }
        }
    }
}

Ninesky.Web/Areas/System/Views/Shared/SystemAside.cshtml
<div class="panel panel-default">
    <div class="panel-heading">
        <h5 class="panel-title"><span class="fa fa-list"></span> 功能列表</h5>
    </div>
    <div class="panel-body">
        <ul class="list-group">
            <li class="list-group-item"><a asp-controller="Module" asp-action="Index"><span class="fa fa-th-large"></span> 模块配置</a></li>
        </ul>
    </div>
</div>

Ninesky.Web/Areas/System/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Ninesky系统管理</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
    </environment>
    <link rel="stylesheet" href="~/Areas/System/css/system.css" />
    <link rel="stylesheet" href="~/lib/bootstrap-select/dist/css/bootstrap-select.min.css" />
    <link rel="stylesheet" href="~/lib/FontAwesome/css/font-awesome.css" />
    <link rel="stylesheet" href="~/lib/ztree/css/metroStyle/metroStyle.css" />
    <link rel="stylesheet" href="~/lib/bootstrap-table/dist/bootstrap-table.min.css" />
    <link rel="stylesheet" href="~/lib/bootstrap3-dialog/dist/css/bootstrap-dialog.min.css" />
    <link rel="stylesheet" href="~/Areas/System/css/system.css" />
    @*@Html.ApplicationInsightsJavaScript(TelemetryConfiguration)*@
</head>
<body>
    <div class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#"> 系统管理</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-controller="Home" asp-action="Index"><span class="fa fa-home"></span> 首页</a></li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="fa fa-folder"></span> 内容管理 <span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                            <li> <a asp-controller="Content" asp-action="List"><span class="fa fa-file"></span> 信息</a></li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="fa fa fa-list"></span> 栏目管理 <span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                            <li> <a asp-area="System" asp-controller="Category" asp-action="Index"><span class="fa fa-folder"></span> 栏目列表</a></li>
                            <li role="separator" class="divider"></li>
                            <li> <a asp-controller="Category" asp-action="Add"><span class="fa fa-folder"></span> 添加常规栏目</a></li>
                            <li> <a href="@Url.Action("Add", "Category",new { categoryType = "Page" })"><span class="fa fa-file"></span> 添加单页栏目</a></li>
                            <li> <a href="@Url.Action("Add", "Category",new { categoryType = "Link" })"><span class="fa fa-link"></span> 添加链接栏目</a></li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="fa fa-cog"></span> 系统配置 <span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                            <li> <a asp-controller="Module" asp-action="Index"><span class="fa fa-th-large"></span> 模块配置</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="body-content">
        <div class="row">
            <aside class="col-md-3" style="padding:20px;">@RenderSection("aside", false)</aside>
            <div class="col-md-9">@RenderBody()</div>
        </div>

        <hr />
        <footer>
            <p>&copy;Ninesky- By 洞庭夕照</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>

    </environment>
    <script src="~/lib/bootstrap-select/dist/js/bootstrap-select.min.js"></script>
    <script src="~/lib/bootstrap-table/dist/bootstrap-table.min.js"></script>
    <script src="~/lib/bootstrap-table/dist/locale/bootstrap-table-zh-CN.min.js"></script>
    <script src="~/lib/ztree/js/jquery.ztree.core.min.js"></script>
    <script src="~/lib/bootstrap3-dialog/dist/js/bootstrap-dialog.min.js"></script>
    <script src="~/Areas/System/js/system.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>